export const dom = {
  elHome: document.getElementById("home-screen"),
  elCal: document.getElementById("calendar-screen"),
  btnCal: document.getElementById("btn-open-calendar"),
  btnBack: document.getElementById("btn-back-home"),
  btnAddHome: document.getElementById("btn-add-event-home"),
  btnAddCal: document.getElementById("btn-add-event-calendar"),
  btnPrev: document.getElementById("btn-prev-month"),
  btnNext: document.getElementById("btn-next-month"),
  elMonth: document.getElementById("month-label"),
  elGrid: document.getElementById("calendar-grid"),
  elSelLbl: document.getElementById("selected-date-label"),
  elTodayList: document.getElementById("today-event-list"),
  elSelList: document.getElementById("selected-day-event-list"),
  elNextBody: document.getElementById("next-event-body"),
  elsViewBtn: document.querySelectorAll(".view-btn"),
  elsNav: document.querySelectorAll(".bottom-nav-btn"),
  btnMulti: document.getElementById("btn-multi-toggle"),

  elMd: document.getElementById("event-modal"),
  elMdTit: document.getElementById("modal-title"),
  fEv: document.getElementById("event-form"),
  inpId: document.getElementById("event-id"),
  inpTitle: document.getElementById("event-title"),
  inpDate: document.getElementById("event-date"),
  inpEndDate: document.getElementById("event-end-date"),
  inpTime: document.getElementById("event-time"),
  selRepeat: document.getElementById("event-repeat"),
  inpRem: document.getElementById("event-remind"),
  inpNote: document.getElementById("event-notes"),
  selType: document.getElementById("event-type"),
  btnEditTypes: document.getElementById("btn-edit-types"),
  btnDel: document.getElementById("btn-delete-event"),
  btnCancel: document.getElementById("btn-cancel-modal"),

  elOv: document.getElementById("overlay"),
  elTypeEditor: document.getElementById("type-editor"),
  btnTypeEditorClose: document.getElementById("btn-type-editor-close")
}
